In [ ]:
!wget -P data/full_dataset/ https://storage.googleapis.com/gresearch/goemotions/data/full_dataset/goemotions_1.csv


--2023-03-17 06:42:27--  https://storage.googleapis.com/gresearch/goemotions/data/full_dataset/goemotions_1.csv
Resolving storage.googleapis.com (storage.googleapis.com)... 108.177.96.128, 108.177.127.128, 172.217.218.128, ...
Connecting to storage.googleapis.com (storage.googleapis.com)|108.177.96.128|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 14174600 (14M) [application/octet-stream]
Saving to: ‘data/full_dataset/goemotions_1.csv’

goemotions_1.csv    100%[===================>]  13.52M  15.8MB/s    in 0.9s    

2023-03-17 06:42:29 (15.8 MB/s) - ‘data/full_dataset/goemotions_1.csv’ saved [14174600/14174600]



In [ ]:
!wget -P data/full_dataset/ https://storage.googleapis.com/gresearch/goemotions/data/full_dataset/goemotions_2.csv


--2023-03-17 06:42:29--  https://storage.googleapis.com/gresearch/goemotions/data/full_dataset/goemotions_2.csv
Resolving storage.googleapis.com (storage.googleapis.com)... 108.177.96.128, 108.177.127.128, 172.217.218.128, ...
Connecting to storage.googleapis.com (storage.googleapis.com)|108.177.96.128|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 14173154 (14M) [application/octet-stream]
Saving to: ‘data/full_dataset/goemotions_2.csv’

goemotions_2.csv    100%[===================>]  13.52M  15.5MB/s    in 0.9s    

2023-03-17 06:42:30 (15.5 MB/s) - ‘data/full_dataset/goemotions_2.csv’ saved [14173154/14173154]



In [ ]:
!wget -P data/full_dataset/ https://storage.googleapis.com/gresearch/goemotions/data/full_dataset/goemotions_3.csv

--2023-03-17 06:42:30--  https://storage.googleapis.com/gresearch/goemotions/data/full_dataset/goemotions_3.csv
Resolving storage.googleapis.com (storage.googleapis.com)... 108.177.96.128, 108.177.127.128, 172.217.218.128, ...
Connecting to storage.googleapis.com (storage.googleapis.com)|108.177.96.128|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 14395164 (14M) [application/octet-stream]
Saving to: ‘data/full_dataset/goemotions_3.csv’

goemotions_3.csv    100%[===================>]  13.73M  16.5MB/s    in 0.8s    

2023-03-17 06:42:31 (16.5 MB/s) - ‘data/full_dataset/goemotions_3.csv’ saved [14395164/14395164]



In [ ]:
import pandas as pd
from collections import Counter

In [ ]:
path_1 = './data/full_dataset/goemotions_1.csv'
d1 = pd.read_csv(path_1)

d1.shape

(70000, 37)

In [ ]:
path_2 = './data/full_dataset/goemotions_2.csv'
d2 = pd.read_csv(path_2)

d2.shape

(70000, 37)

In [ ]:
path_3 = './data/full_dataset/goemotions_3.csv'
d3 = pd.read_csv(path_3)

d3.shape

(71225, 37)

In [ ]:
cols = ["text", "id", "admiration", "annoyance"]
df = d1[['id','text','admiration','annoyance']]

In [ ]:
df.shape

(70000, 4)

In [ ]:
df_all = pd.concat([d1,d2,d3])

In [ ]:
df_all.shape, (len(d1) + len(d2) + len(d3))

((211225, 37), 211225)

In [ ]:
df_all.head(1).T

0
text                  That game hurt.
id                            eew5j0j
author                          Brdd9
subreddit                         nrl
link_id                     t3_ajis4z
parent_id                  t1_eew18eq
created_utc              1548381039.0
rater_id                            1
example_very_unclear            False
admiration                          0
amusement                           0
anger                               0
annoyance                           0
approval                            0
caring                              0
confusion                           0
curiosity                           0
desire                              0
disappointment                      0
disapproval                         0
disgust                             0
embarrassment                       0
excitement                          0
fear                                0
gratitude                           0
grief                               0
joy                                 0
love                                0
nervousness                         0
optimism                            0
pride                               0
realization                         0
relief                              0
remorse                             0
sadness                             1
surprise                            0
neutral                             0

In [ ]:
cols = ["text", "id", "admiration", "annoyance"]
df = df_all[['id','text','admiration','annoyance']]

In [ ]:
df.admiration.value_counts(normalize = True)


0    0.918897
1    0.081103
Name: admiration, dtype: float64

In [ ]:
Counter(df.admiration)

Counter({0: 194094, 1: 17131})

In [ ]:
Counter(df.annoyance)

Counter({0: 197607, 1: 13618})

In [ ]:
df.annoyance.value_counts(normalize = True)

0    0.935528
1    0.064472
Name: annoyance, dtype: float64

In [ ]:
df_admiration = df_all[df_all.admiration == 1]
df_annoyance = df_all[df_all.annoyance == 1]

In [ ]:
data_admiration = df_admiration.text.tolist()
data_annoyance = df_annoyance.text.tolist()

In [ ]:
adm_len = len(data_admiration)
ann_len = len(data_annoyance)

adm_len/(adm_len + ann_len), ann_len/(adm_len + ann_len)

(0.5571238089043546, 0.4428761910956454)

In [ ]:
data_annoyance[:10]

["For extra measure tape it right by your crotch so she can't take it for sexual assault reasons",
 'Go troll elsewhere. This woman needs support, not crass questions.',
 "Just rumors online, it most likely won't happen",
 'Good old guardian refusing to accept that [NAME] is stauncly anti-EU and anti-Brussels',
 "Do you not give your snowmen brooms? I feel like that's a thing people do",
 'Calm down.',
 'I mean that’s a stupid rule that creates an echo chamber, but I don’t see how that belongs here.',
 "[NAME] has always favoured [NAME] so I'd assume this means he's the next up, I just prefer [NAME] and find [NAME] a little overrated.",
 'Yes, at home recuperating from a fractured ankle. ',
 'So wrong. Most every denomination believes they are the only ones who are doing it right and everyone else is going to rot in hell.']

In [ ]:
idx = 20
data_annoyance[idx:idx+10]

['What a douche canoe to take advantage of you like that.',
 'Man I hate kids',
 "[NAME] damn it I'm so tired of seeing Instagram between fights",
 'Who still unironically says SJWs? You look like an idiot saying that.',
 'I have a deep seeded hatred for close-minded people too.',
 'Look [NAME] is here "Where the fuck was he an hour ago, gary, where!?"',
 'State of [NAME] trying to be funny and spelling ‘lose’ wrong',
 'That sucks! Your lady giblets are NONE of her damn business. Does your BF at least try to curb her mouth?',
 'dude people here can be assholes. there’s nothing wrong with taking a break.',
 "He told you that he hates your friends because they don't beat you up? That is so disgusting!"]

In [ ]:
data_admiration[:10]

["I appreciate it, that's good to know. I hope I'll have to apply that knowledge one day",
 "Pretty much every Punjabi dude I've met.",
 'Lots, play store or apple store vpn. Nord is good',
 "nice!! I'll try this one",
 'She’s like a kewpie doll with them. Precious.',
 "Nice. I'll look around for it. Thanks!",
 'I loved how [NAME] feels like everyone in the office is her family. Her relationship with [NAME] is so cute and innocent',
 'I thought it was very good. The guy was one sick bastard that’s for sure.',
 'Best side quest ever!',
 'I love that smile of his!!!!']

In [ ]:
from sklearn.model_selection import train_test_split


labeled_texts = []
for text in data_admiration:
    labeled_texts.append((text, 1))
for text in data_annoyance:
    labeled_texts.append((text, 0))

train_texts, test_texts, train_labels, test_labels = train_test_split(
    [text[0] for text in labeled_texts], 
    [text[1] for text in labeled_texts], 
    test_size=0.1,                       
    random_state=42,                     
    stratify=[text[1] for text in labeled_texts] 
)


In [ ]:
len(train_texts), len(test_texts), Counter(train_labels), Counter(test_labels)

(27674, 3075, Counter({1: 15418, 0: 12256}), Counter({1: 1713, 0: 1362}))

In [ ]:
!pip install -q transformers

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6.7/6.7 MB 75.6 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 199.2/199.2 KB 28.8 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.6/7.6 MB 105.5 MB/s eta 0:00:00


In [ ]:
from transformers import DistilBertTokenizerFast
tokenizer = DistilBertTokenizerFast.from_pretrained('distilbert-base-uncased')

In [ ]:
len(train_texts), Counter(train_labels)

(27674, Counter({1: 15418, 0: 12256}))

In [ ]:
train_texts, val_texts, train_labels, val_labels = train_test_split(train_texts,
                                                                    train_labels,
                                                                    test_size=0.1, 
                                                                    random_state = 42)

In [ ]:
len(train_texts) + len(val_texts), Counter(train_labels), Counter(val_labels)

(27674, Counter({1: 13896, 0: 11010}), Counter({0: 1246, 1: 1522}))

In [ ]:
#train_texts, train_labels
#val_texts, val_labels
#test_texts, test_labels

In [ ]:
tokenizer.max_len_single_sentence

510

In [ ]:
train_encodings = tokenizer(train_texts, truncation=True, padding=True)
val_encodings = tokenizer(val_texts, truncation=True, padding=True)
test_encodings = tokenizer(test_texts, truncation=True, padding=True)

In [ ]:
len(train_texts), len(train_encodings), 

(24906, 2)

In [ ]:

train_encodings[24905].encoding

AttributeError: ignored

In [ ]:
# train_encodings[0].tokens[:30], train_encodings[0].attention_mask[:30], train_encodings[0].special_tokens_mask[:30]

In [ ]:
import torch

class dataset(torch.utils.data.Dataset):
    def __init__(self, encodings, labels):
        self.encodings = encodings
        self.labels = labels

    def __getitem__(self, idx):
        item = {key: torch.tensor(val[idx]) for key, val in self.encodings.items()}
        item['labels'] = torch.tensor(self.labels[idx])
        return item

    def __len__(self):
        return len(self.labels)

train_dataset = dataset(train_encodings, train_labels)
val_dataset = dataset(val_encodings, val_labels)
test_dataset = dataset(test_encodings, test_labels)

In [ ]:
len(train_dataset.labels), len(train_dataset.encodings)

(24906, 2)

In [ ]:

from torch.utils.data import DataLoader
from transformers import DistilBertForSequenceClassification, AdamW

device = torch.device('cuda') if torch.cuda.is_available() else torch.device('cpu')

model = DistilBertForSequenceClassification.from_pretrained('distilbert-base-uncased')
model.to(device)
model.train()

train_loader = DataLoader(train_dataset, batch_size=16, shuffle=True)

optim = AdamW(model.parameters(), lr=5e-5)

Some weights of the model checkpoint at distilbert-base-uncased were not used when initializing DistilBertForSequenceClassification: ['vocab_layer_norm.bias', 'vocab_projector.weight', 'vocab_transform.bias', 'vocab_layer_norm.weight', 'vocab_transform.weight', 'vocab_projector.bias']
- This IS expected if you are initializing DistilBertForSequenceClassification from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing DistilBertForSequenceClassification from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
Some weights of DistilBertForSequenceClassification were not initialized from the model checkpoint at distilbert-base-uncased and are newly initialized: ['pre_classifier.weight', 'pre_classifier.bias', 'classi

In [ ]:
len(train_dataset)

24906

In [ ]:
for epoch in range(3):
  print(f"epoch - {epoch}")
  bt = 0
  for batch in train_loader:
      optim.zero_grad()
      input_ids = batch['input_ids'].to(device)
      attention_mask = batch['attention_mask'].to(device)
      labels = batch['labels'].to(device)
      outputs = model(input_ids, attention_mask=attention_mask, labels=labels)
      loss = outputs[0]
      if bt % 500 == 0:
        print(f"epoch - {epoch} batch - {bt} - loss - {loss.item()}")
      bt += 1
      loss.backward()
      optim.step()
  print(f"end of epoch {epoch} - total batches - {bt}")

epoch - 0
epoch - 0 batch - 0 - loss - 0.6789759397506714
epoch - 0 batch - 500 - loss - 0.10679575800895691
epoch - 0 batch - 1000 - loss - 0.09133709967136383
epoch - 0 batch - 1500 - loss - 0.5891621708869934
end of epoch 0 - total batches - 1557
epoch - 1
epoch - 1 batch - 0 - loss - 0.05004775524139404
epoch - 1 batch - 500 - loss - 0.19975194334983826
epoch - 1 batch - 1000 - loss - 0.4474211633205414
epoch - 1 batch - 1500 - loss - 0.3487479090690613
end of epoch 1 - total batches - 1557
epoch - 2
epoch - 2 batch - 0 - loss - 0.10343366116285324
epoch - 2 batch - 500 - loss - 0.05225159972906113
epoch - 2 batch - 1000 - loss - 0.14451129734516144
epoch - 2 batch - 1500 - loss - 0.047133270651102066
end of epoch 2 - total batches - 1557


In [ ]:
# model.eval()

In [ ]:
val_loader = DataLoader(val_dataset, batch_size=16, shuffle=True)

In [ ]:
# model.eval()

In [ ]:

val_texts[:3]

['The general rule is that [NAME] is talking rubbish whenever he opens his mouth.',
 'I for one think that the military of no country should be this strong either.',
 'Your Mom was ruled by [NAME] dynasty that happened to be Macedonian for the next three centuries.']

In [ ]:
txts = val_texts[:10]

txts_enc = tokenizer(txts, truncation=True, padding=True)
txts_dataset = dataset(txts_enc, None)


In [ ]:
txts = [
    "Actually, it's pronounced...",
    "Well, *actually*...",
    "I'm sorry, but I can't help but correct you...",
    "I can't believe you don't know that...",
    "Um, excuse me, but...",
    "That's not how it works, let me explain...",
    "You're wrong, let me tell you why...",
    "I hate to be that person, but...",
    "Can I just say something?",
    "I'm not trying to be rude, but...",
    "You should already know this...",
    "I'm surprised you haven't heard of this before...",
    "I'm just trying to help you improve...",
    "I think you're mistaken...",
    "I'm sorry, but that's just not true...",
    "Do you even know what you're talking about?",
    "You're missing the point...",
    "It's not that difficult to understand...",
    "I don't think you get it...",
    "You need to educate yourself on this topic...",
]


In [ ]:
txts = [
    "I admire your dedication to your craft.",
    "You have an incredible work ethic that I look up to.",
    "I am in awe of your ability to think creatively and solve problems.",
    "You inspire me with your passion for making the world a better place.",
    "Your perseverance in the face of adversity is truly inspiring.",
    "I am impressed by your ability to stay calm and focused under pressure.",
    "Your kindness and empathy towards others is something I aspire to.",
    "I have the utmost respect for your honesty and integrity.",
    "You have a unique perspective that I find fascinating and enlightening.",
    "Your generosity and willingness to help others is truly admirable."
]


In [ ]:
encoded_texts = tokenizer(txts, padding=True, truncation=True, return_tensors='pt').to(device)
outputs = model(encoded_texts['input_ids'], attention_mask=encoded_texts['attention_mask'])
outs = F.softmax(outputs.logits, dim = 1)
predicted_labels = torch.argmax(outs, dim=1)
predicted_labels

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1], device='cuda:0')

In [ ]:
outs


tensor([[6.4267e-04, 9.9936e-01],
        [6.9036e-04, 9.9931e-01],
        [1.3843e-01, 8.6157e-01],
        [8.1132e-04, 9.9919e-01],
        [2.2913e-02, 9.7709e-01],
        [2.4930e-03, 9.9751e-01],
        [2.6843e-02, 9.7316e-01],
        [7.0157e-04, 9.9930e-01],
        [6.8766e-04, 9.9931e-01],
        [2.8995e-03, 9.9710e-01]], device='cuda:0', grad_fn=<SoftmaxBackward0>)

<ipython-input-128-5b3713794976>:1: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  F.softmax(outputs.logits)


tensor([[7.1340e-04, 9.9929e-01]], device='cuda:0', grad_fn=<SoftmaxBackward0>)

In [ ]:
txts_dataset.encodings

{'input_ids': [[101, 2008, 2015, 2428, 2307, 3105, 2567, 1010, 1045, 19837, 2115, 7729, 102, 0, 0, 0], [101, 1045, 2064, 1005, 1056, 8622, 2032, 1010, 2064, 2002, 2074, 6616, 2125, 2085, 999, 102]], 'attention_mask': [[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0], [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]]}

In [ ]:

model(txts_dataset.encodings.input_ids, attention_mask=txts_dataset.encodings.attention_mask)

AttributeError: ignored

In [ ]:
txts_enc

{'input_ids': [[101, 2008, 2015, 2428, 2307, 3105, 2567, 1010, 1045, 19837, 2115, 7729, 102, 0, 0, 0], [101, 1045, 2064, 1005, 1056, 8622, 2032, 1010, 2064, 2002, 2074, 6616, 2125, 2085, 999, 102]], 'attention_mask': [[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0], [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]]}

In [ ]:

device

device(type='cuda')

In [ ]:
ips = torch.Tensor(txts_enc.input_ids)
am = torch.Tensor(txts_enc.attention_mask)
ips = ips.to(device)
am = am.to(device)

In [ ]:
# model(ips, attention_mask = am)

In [ ]:
for batch in train_loader:
  tb = batch
  input_ids = batch['input_ids'].to(device)
  attention_mask = batch['attention_mask'].to(device)
  labels = batch['labels'].to(device)
  outputs = model(input_ids, attention_mask=attention_mask)
  break

In [ ]:
outputs.logits.shape

torch.Size([16, 2])

In [ ]:
F.softmax(outputs.logits)

<ipython-input-101-5b3713794976>:1: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  F.softmax(outputs.logits)


tensor([[9.8584e-01, 1.4157e-02],
        [2.1578e-03, 9.9784e-01],
        [3.3390e-03, 9.9666e-01],
        [9.9215e-01, 7.8513e-03],
        [1.8199e-01, 8.1801e-01],
        [9.9239e-01, 7.6119e-03],
        [9.7958e-01, 2.0423e-02],
        [9.9270e-01, 7.3036e-03],
        [7.8171e-01, 2.1829e-01],
        [5.1501e-03, 9.9485e-01],
        [1.8676e-01, 8.1324e-01],
        [9.9051e-01, 9.4920e-03],
        [8.6019e-01, 1.3981e-01],
        [1.0404e-03, 9.9896e-01],
        [4.0835e-01, 5.9165e-01],
        [8.9042e-04, 9.9911e-01]], device='cuda:0', grad_fn=<SoftmaxBackward0>)

In [ ]:
import torch.nn.functional as F

In [ ]:
F.softmax(outputs.logits)

<ipython-input-98-5b3713794976>:1: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  F.softmax(outputs.logits)


tensor([[9.9176e-01, 8.2382e-03],
        [9.9236e-01, 7.6358e-03],
        [2.5345e-03, 9.9747e-01],
        [7.6250e-01, 2.3750e-01],
        [7.6553e-04, 9.9923e-01],
        [9.9090e-01, 9.1043e-03],
        [9.9415e-01, 5.8475e-03],
        [9.8687e-01, 1.3133e-02],
        [8.9414e-04, 9.9911e-01],
        [1.0758e-03, 9.9892e-01],
        [9.6688e-01, 3.3124e-02],
        [2.3114e-02, 9.7689e-01],
        [9.9457e-01, 5.4306e-03],
        [8.4372e-01, 1.5628e-01],
        [9.8910e-01, 1.0901e-02],
        [2.3501e-02, 9.7650e-01]], device='cuda:0', grad_fn=<SoftmaxBackward0>)

In [ ]:
for batch in val_loader:
  outs = model(batch)
  break

AttributeError: ignored

In [ ]:
16 * 1557

24912

In [ ]:
save_directory = './'
tokenizer.save_pretrained(save_directory)
model.save_pretrained(save_directory)

In [ ]:
val_dataset = dataset(val_encodings, val_labels)
test_dataset = dataset(test_encodings, test_labels)